version: "2"

linters:
  enable:
    - exhaustruct
  settings:
    exhaustruct:
      include:
        - 'github\.com/onlyati/quadlet-lsp/internal/semantic\..*'
        - 'github\.com/onlyati/quadlet-lsp/pkg/quadlet/lexer\..*'
