version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: quadlet-lsp
    formats:
      - tar.gz
    format_overrides:
      - formats:
          - zip
        goos: windows
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

nfpms:
  - id: quadlet-lsp
    package_name: quadlet-lsp
    vendor: onlyati
    homepage: https://github.com/onlyati/quadlet-lsp
    maintainer: Attila Molnár <onlyati@pm.me>
    description: |-
      This is an implementation of language server for Podman Quadlet files.
    license: GPL 3.0
    formats:
      - deb
      - rpm
    dependencies: []
    recommends:
      - podman
    suggests: []
    section: default
    rpm:
      summary: Podman Quadlet language server
      group: Development/Tools
      compression: gzip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
