name: Feature request
description: Ask a request
labels: ["enhancement"]
assignees:
  - onlyati
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: description
    attributes:
      label: Motivation
      description:
        Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative options
      description: Describe alternatives you've considered
    validations:
      required: true
  - type: textarea
    id: documents
    attributes:
      label: Additional documents
      description:
        If you can provide some official documents that can help the
        development, please link them here.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the feature
    validations:
      required: true
